version: '2'

services:
  alluxio-master:
    build: docker-alluxio-base
    command: /start.sh master
    ports:
      - 19999:19999
      - 19998:19998
      - 30000:30000
    volumes:
      - data:/data
    environment:
      ALLUXIO_MASTER_ADDRESS: alluxio-master



  alluxio-slave:
    build: docker-alluxio-base
    command: /start.sh slave
    ports:
      - 29998:29998
      - 29999:29999
    links:
      - alluxio-master
    volumes:
      - data:/data
    ## change to your DOCKER_HOST
    hostname: 192.168.99.100

    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
    environment:
      ALLUXIO_MASTER_ADDRESS: alluxio-master


## Run everything in one container
#  alluxio-local:
#    build: docker-alluxio-base
#    command: /start.sh local
#    ports:
#      - 19999:19999
#      - 19998:19998
#      - 30000:30000
#      - 29998:29998
#      - 29999:29999
#    ## change to your DOCKER_HOST
#    hostname: 192.168.99.100
#    #    privileged: true         ### enable to use ramfs with docker. otherwise it will use disk
#    volumes:
#      - data:/data
#    environment:
#      ALLUXIO_MASTER_ADDRESS: 192.168.99.100



volumes:
  data:


